// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protofiles/meteo-streaming/meteo_streaming.proto

package meteo_streaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescGZIP(), []int{0}
}

type CurrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature2M float32                `protobuf:"fixed32,1,opt,name=Temperature2M,proto3" json:"Temperature2M,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentResponse) Reset() {
	*x = CurrentResponse{}
	mi := &file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentResponse) ProtoMessage() {}

func (x *CurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentResponse.ProtoReflect.Descriptor instead.
func (*CurrentResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentResponse) GetTemperature2M() float32 {
	if x != nil {
		return x.Temperature2M
	}
	return 0
}

var File_protofiles_meteo_streaming_meteo_streaming_proto protoreflect.FileDescriptor

const file_protofiles_meteo_streaming_meteo_streaming_proto_rawDesc = "" +
	"\n" +
	"0protofiles/meteo-streaming/meteo_streaming.proto\x12\n" +
	"protofiles\"\a\n" +
	"\x05Empty\"7\n" +
	"\x0fCurrentResponse\x12$\n" +
	"\rTemperature2M\x18\x01 \x01(\x02R\rTemperature2M2a\n" +
	"\x14MeteoStremingService\x12I\n" +
	"\x13GetCurrentStreaming\x12\x11.protofiles.Empty\x1a\x1b.protofiles.CurrentResponse\"\x000\x01B\x1cZ\x1aprotofiles/meteo_streamingb\x06proto3"

var (
	file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescOnce sync.Once
	file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescData []byte
)

func file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescGZIP() []byte {
	file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescOnce.Do(func() {
		file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protofiles_meteo_streaming_meteo_streaming_proto_rawDesc), len(file_protofiles_meteo_streaming_meteo_streaming_proto_rawDesc)))
	})
	return file_protofiles_meteo_streaming_meteo_streaming_proto_rawDescData
}

var file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_meteo_streaming_meteo_streaming_proto_goTypes = []any{
	(*Empty)(nil),           // 0: protofiles.Empty
	(*CurrentResponse)(nil), // 1: protofiles.CurrentResponse
}
var file_protofiles_meteo_streaming_meteo_streaming_proto_depIdxs = []int32{
	0, // 0: protofiles.MeteoStremingService.GetCurrentStreaming:input_type -> protofiles.Empty
	1, // 1: protofiles.MeteoStremingService.GetCurrentStreaming:output_type -> protofiles.CurrentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_meteo_streaming_meteo_streaming_proto_init() }
func file_protofiles_meteo_streaming_meteo_streaming_proto_init() {
	if File_protofiles_meteo_streaming_meteo_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protofiles_meteo_streaming_meteo_streaming_proto_rawDesc), len(file_protofiles_meteo_streaming_meteo_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_meteo_streaming_meteo_streaming_proto_goTypes,
		DependencyIndexes: file_protofiles_meteo_streaming_meteo_streaming_proto_depIdxs,
		MessageInfos:      file_protofiles_meteo_streaming_meteo_streaming_proto_msgTypes,
	}.Build()
	File_protofiles_meteo_streaming_meteo_streaming_proto = out.File
	file_protofiles_meteo_streaming_meteo_streaming_proto_goTypes = nil
	file_protofiles_meteo_streaming_meteo_streaming_proto_depIdxs = nil
}
