// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.2
// source: protofiles/meteo-streaming/meteo_streaming.proto

package meteo_streaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeteoStremingServiceClient is the client API for MeteoStremingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeteoStremingServiceClient interface {
	GetCurrentStreaming(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MeteoStremingService_GetCurrentStreamingClient, error)
}

type meteoStremingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeteoStremingServiceClient(cc grpc.ClientConnInterface) MeteoStremingServiceClient {
	return &meteoStremingServiceClient{cc}
}

func (c *meteoStremingServiceClient) GetCurrentStreaming(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MeteoStremingService_GetCurrentStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &MeteoStremingService_ServiceDesc.Streams[0], "/protofiles.MeteoStremingService/GetCurrentStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &meteoStremingServiceGetCurrentStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeteoStremingService_GetCurrentStreamingClient interface {
	Recv() (*CurrentResponse, error)
	grpc.ClientStream
}

type meteoStremingServiceGetCurrentStreamingClient struct {
	grpc.ClientStream
}

func (x *meteoStremingServiceGetCurrentStreamingClient) Recv() (*CurrentResponse, error) {
	m := new(CurrentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeteoStremingServiceServer is the server API for MeteoStremingService service.
// All implementations must embed UnimplementedMeteoStremingServiceServer
// for forward compatibility
type MeteoStremingServiceServer interface {
	GetCurrentStreaming(*Empty, MeteoStremingService_GetCurrentStreamingServer) error
	mustEmbedUnimplementedMeteoStremingServiceServer()
}

// UnimplementedMeteoStremingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeteoStremingServiceServer struct {
}

func (UnimplementedMeteoStremingServiceServer) GetCurrentStreaming(*Empty, MeteoStremingService_GetCurrentStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCurrentStreaming not implemented")
}
func (UnimplementedMeteoStremingServiceServer) mustEmbedUnimplementedMeteoStremingServiceServer() {}

// UnsafeMeteoStremingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeteoStremingServiceServer will
// result in compilation errors.
type UnsafeMeteoStremingServiceServer interface {
	mustEmbedUnimplementedMeteoStremingServiceServer()
}

func RegisterMeteoStremingServiceServer(s grpc.ServiceRegistrar, srv MeteoStremingServiceServer) {
	s.RegisterService(&MeteoStremingService_ServiceDesc, srv)
}

func _MeteoStremingService_GetCurrentStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeteoStremingServiceServer).GetCurrentStreaming(m, &meteoStremingServiceGetCurrentStreamingServer{stream})
}

type MeteoStremingService_GetCurrentStreamingServer interface {
	Send(*CurrentResponse) error
	grpc.ServerStream
}

type meteoStremingServiceGetCurrentStreamingServer struct {
	grpc.ServerStream
}

func (x *meteoStremingServiceGetCurrentStreamingServer) Send(m *CurrentResponse) error {
	return x.ServerStream.SendMsg(m)
}

// MeteoStremingService_ServiceDesc is the grpc.ServiceDesc for MeteoStremingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeteoStremingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.MeteoStremingService",
	HandlerType: (*MeteoStremingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCurrentStreaming",
			Handler:       _MeteoStremingService_GetCurrentStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protofiles/meteo-streaming/meteo_streaming.proto",
}
